### ISSUE TITLE
Make Plugins for EaglerForge?

### ISSUE THREAD

**Issue by STPv22** [wxnnvs/reborn-plugins#1]
org:eaglerforge

**Comment by wxnnvs** [comment]
what do you mean

**Comment by STPv22** [comment]
https://github.com/eaglerforge/

it's based on the eaglerreborn plugin system, but they have added a lot to the API. I think it might be possible to make features for the client.

**Comment by wxnnvs** [comment]
look at the latest commit bro 🤦‍♂️
